import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { issueAccessToken, verifyAccessToken } from './auth.mjs';
import { config } from './config.mjs';

const prisma = new PrismaClient();
const port = config.port;
const allowedOrigins = config.corsOrigins;
function headers(req, res) { const origin = req.headers.origin; res.setHeader('access-control-allow-origin', allowedOrigins.includes('*') || allowedOrigins.includes(origin) ? (origin || '*') : allowedOrigins[0]); res.setHeader('vary', 'Origin'); res.setHeader('access-control-allow-headers', 'content-type, authorization, idempotency-key'); res.setHeader('access-control-allow-methods', 'GET,POST,PATCH,OPTIONS'); res.setHeader('content-type', 'application/json; charset=utf-8'); }
function send(req, res, status, data, error = null) { headers(req, res); res.statusCode = status; res.end(JSON.stringify({ data, meta: { requestId: randomUUID(), timestamp: new Date().toISOString() }, error })); }
function fail(req, res, status, code, message) { return send(req, res, status, null, { code, message }); }
async function readBody(req) { let raw = ''; for await (const chunk of req) raw += chunk; return raw ? JSON.parse(raw) : {}; }
async function currentUser(req) { const claims = verifyAccessToken((req.headers.authorization || '').replace(/^Bearer\s+/i, '')); if (!claims) return null; return prisma.user.findUnique({ where: { id: claims.sub }, include: { memberships: { include: { organization: true } } } }); }
function membership(user, role) { return user?.memberships.find(item => item.role === role || (role === 'buyer' && item.role === 'BUYER_ADMIN') || (role === 'seller' && item.role === 'SELLER_ADMIN') || role === 'admin' && item.role === 'PLATFORM_ADMIN'); }
function mapRfq(r) { return { id: r.rfqCode, title: r.title, buyer: r.buyerOrganization.displayName || r.buyerOrganization.legalName, buyerOrganizationId: r.buyerOrganizationId, grade: r.gradeRequired, quantity: `${r.quantityTonnes} t`, delivery: `${r.deliveryCity || ''}, ${r.deliveryState || ''}`, budget: `₹${r.budgetMinInrPerTonne || 0}–${r.budgetMaxInrPerTonne || 0}/t delivered`, status: r.status.toLowerCase().replace('_', '-'), bids: r.bids.length }; }
function mapBid(b) { return { id: b.bidCode, rfqId: b.rfq.rfqCode, supplier: b.sellerOrganization.displayName || b.sellerOrganization.legalName, sellerOrganizationId: b.sellerOrganizationId, listing: b.listing.listingCode, quantity: `${b.quantityTonnes} t`, price: `₹${b.exWorksPriceInrPerTonne}/t`, delivered: `₹${b.deliveredPriceInrPerTonne}/t`, leadTime: `${b.leadTimeBusinessDays} business days`, evidence: b.evidenceSummary || 'Evidence under review', status: b.status.toLowerCase(), }; }
const server = http.createServer(async (req, res) => {
  if (req.method === 'OPTIONS') { headers(req, res); res.statusCode = 204; return res.end(); }
  if (req.url === '/health') { try { await prisma.$queryRaw`SELECT 1`; return send(req, res, 200, { status: 'ok', service: 'carbon-connect-prisma-api', database: 'postgresql' }); } catch { return fail(req, res, 503, 'DATABASE_UNAVAILABLE', 'Database is not ready.'); } }
  if (!req.url.startsWith('/api/v1/')) return fail(req, res, 404, 'NOT_FOUND', 'API route not found.');
  try {
    if (req.url === '/api/v1/auth/login' && req.method === 'POST') {
      const input = await readBody(req); const user = await prisma.user.findUnique({ where: { email: input.email }, include: { memberships: true } }); const match = user?.memberships.find(m => m.role.startsWith(String(input.role || '').toUpperCase())) || user?.memberships[0];
      if (!user || user.passwordHash !== input.password || !match) return fail(req, res, 401, 'INVALID_CREDENTIALS', 'Invalid credentials.');
      return send(req, res, 200, { token: issueAccessToken({ id: user.id, role: input.role, organizationId: match.organizationId }), user: { id: user.id, email: user.email, role: input.role, organizationId: match.organizationId } });
    }
    const user = await currentUser(req); if (!user) return fail(req, res, 401, 'UNAUTHENTICATED', 'A valid signed session is required.');
    if (req.url === '/api/v1/rfqs' && req.method === 'GET') { const rows = await prisma.rfq.findMany({ include: { buyerOrganization: true, bids: true }, orderBy: { createdAt: 'desc' } }); return send(req, res, 200, rows.map(mapRfq)); }
    if (req.url === '/api/v1/rfqs' && req.method === 'POST') { const m = membership(user, 'buyer'); if (!m) return fail(req, res, 403, 'FORBIDDEN', 'Buyer membership required.'); const input = await readBody(req); const created = await prisma.rfq.create({ data: { rfqCode: `CC-RFQ-${Date.now()}`, buyerOrganizationId: m.organizationId, createdBy: user.id, title: input.title, gradeRequired: input.grade || input.gradeRequired || 'Captured CO₂', quantityTonnes: Number(String(input.quantity || '0').replace(/[^0-9.]/g, '')), deliveryAddress: input.deliveryAddress || input.delivery || 'To be confirmed', deliveryCity: input.city || 'Mumbai', deliveryState: input.state || 'Maharashtra', status: 'PUBLISHED', publishedAt: new Date(), budgetMinInrPerTonne: Number(input.budgetMin || 0), budgetMaxInrPerTonne: Number(input.budgetMax || 0) }, include: { buyerOrganization: true, bids: true } }); return send(req, res, 201, mapRfq(created)); }
    const rfqBids = req.url.match(/^\/api\/v1\/rfqs\/([^/]+)\/bids$/);
    if (rfqBids && req.method === 'GET') { const rfq = await prisma.rfq.findUnique({ where: { rfqCode: rfqBids[1] } }); if (!rfq) return fail(req, res, 404, 'RFQ_NOT_FOUND', 'RFQ not found.'); const rows = await prisma.bid.findMany({ where: { rfqId: rfq.id }, include: { rfq: true, listing: true, sellerOrganization: true }, orderBy: { createdAt: 'asc' } }); return send(req, res, 200, rows.map(mapBid)); }
    if (rfqBids && req.method === 'POST') { const m = membership(user, 'seller'); if (!m) return fail(req, res, 403, 'FORBIDDEN', 'Seller membership required.'); const rfq = await prisma.rfq.findUnique({ where: { rfqCode: rfqBids[1] } }); if (!rfq || !['PUBLISHED', 'BIDS_RECEIVED'].includes(rfq.status)) return fail(req, res, 409, 'RFQ_NOT_OPEN', 'RFQ is not accepting bids.'); const input = await readBody(req); const listing = await prisma.listing.findFirst({ where: { organizationId: m.organizationId, status: 'PUBLISHED' } }); if (!listing) return fail(req, res, 409, 'LISTING_REQUIRED', 'A published seller listing is required.'); const duplicate = await prisma.bid.findFirst({ where: { rfqId: rfq.id, sellerOrganizationId: m.organizationId, status: { in: ['SUBMITTED', 'SHORTLISTED'] } } }); if (duplicate) return fail(req, res, 409, 'DUPLICATE_BID', 'Your organization already has an active bid.'); const exWorks = Number(String(input.price || '0').replace(/[^0-9.]/g, '')); const delivered = Number(String(input.delivered || exWorks + 6).replace(/[^0-9.]/g, '')); const created = await prisma.bid.create({ data: { bidCode: `CC-BID-${Date.now()}`, rfqId: rfq.id, sellerOrganizationId: m.organizationId, listingId: listing.id, quantityTonnes: Number(String(input.quantity || rfq.quantityTonnes).replace(/[^0-9.]/g, '')), exWorksPriceInrPerTonne: exWorks, logisticsPriceInrPerTonne: Math.max(0, delivered - exWorks), deliveredPriceInrPerTonne: delivered, totalEstimatedValueInr: delivered * Number(rfq.quantityTonnes), leadTimeBusinessDays: Number(String(input.leadTime || '5').replace(/[^0-9]/g, '')) || 5, evidenceSummary: input.evidence || 'Evidence under review', status: 'SUBMITTED', submittedAt: new Date() }, include: { rfq: true, listing: true, sellerOrganization: true } }); await prisma.rfq.update({ where: { id: rfq.id }, data: { status: 'BIDS_RECEIVED' } }); return send(req, res, 201, mapBid(created)); }
    const award = req.url.match(/^\/api\/v1\/rfqs\/([^/]+)\/award$/);
    if (award && req.method === 'POST') { const m = membership(user, 'buyer'); if (!m) return fail(req, res, 403, 'FORBIDDEN', 'Buyer membership required.'); const input = await readBody(req); const result = await prisma.$transaction(async tx => { const rfq = await tx.rfq.findUnique({ where: { rfqCode: award[1] }, include: { award: true } }); if (!rfq || rfq.buyerOrganizationId !== m.organizationId) throw new Error('FORBIDDEN'); if (rfq.award) return rfq.award; const bid = await tx.bid.findUnique({ where: { bidCode: input.bidId }, include: { sellerOrganization: true } }); if (!bid || bid.rfqId !== rfq.id || !['SUBMITTED', 'SHORTLISTED'].includes(bid.status)) throw new Error('BID_NOT_FOUND'); await tx.bid.updateMany({ where: { rfqId: rfq.id }, data: { status: 'DECLINED' } }); await tx.bid.update({ where: { id: bid.id }, data: { status: 'AWARDED' } }); await tx.rfq.update({ where: { id: rfq.id }, data: { status: 'AWARDED', awardedBidId: bid.id } }); return tx.award.create({ data: { rfqId: rfq.id, bidId: bid.id, buyerOrganizationId: m.organizationId, sellerOrganizationId: bid.sellerOrganizationId, awardedBy: user.id }, }); }); return send(req, res, 201, result); }
    return fail(req, res, 404, 'NOT_FOUND', 'API route not found.');
  } catch (error) { if (error.code === 'P2002' && req.url.includes('/award')) { const code = req.url.match(/^\/api\/v1\/rfqs\/([^/]+)\/award$/)?.[1]; const existing = code ? await prisma.award.findFirst({ where: { rfq: { rfqCode: code } } }).catch(() => null) : null; if (existing) return send(req, res, 200, existing); } if (error.message === 'FORBIDDEN') return fail(req, res, 403, 'FORBIDDEN', 'You do not have access to this organization or RFQ.'); if (error.message === 'BID_NOT_FOUND') return fail(req, res, 404, 'BID_NOT_FOUND', 'Bid not found or no longer active.'); console.error(error); return fail(req, res, 500, 'INTERNAL_ERROR', 'Unexpected server error.'); }
});
server.listen(port, '0.0.0.0', () => console.log(`Carbon-Connect Prisma API listening on 0.0.0.0:${port}`));

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, async () => {
    await prisma.$disconnect();
    process.exit(0);
  });
}
